import React from 'react';
import AvancedTechnology from '../../../assets/landing-page-assets/AdvancedTechnology.svg';
import VideoMatching from '../../../assets/landing-page-assets/DrivingVideo.png';
import {useAuth} from "../../../contexts/Authentication";

export interface SelfSupervisedLearningSectionProps {
  className?: string;
}

export const SelfSupervisedLearningSection : React.FC<SelfSupervisedLearningSectionProps> = ({className}) => {
  const {authState} = useAuth();

  return <section className={className + ' container flex flex-col gap-5 h-[170vh] sm:h-[60vh] justify-start overflow-hidden relative'}>
    {/* Background ~ eh... it's good enough for now*/}
    <div className='absolute w-full h-full top-0 left-0 z-10 opacity-50 flex flex-col justify-evenly items-center'>
      {
        [1,2,3].map((item) => {
        return <img key={item} className='rotate-45 p-10 m-5 max-w-max w-[200vw]' src={AvancedTechnology} alt='Advanced Technology' />
        })
      }
    </div>

    {/* Foreground */}
    <div className='absolute z-20 w-full h-full flex flex-col gap-2'>

      {/* Title Section */}
      <h1 className='text-title text-white'>Human Reinforcement Learning </h1>
      <span className='text-white'>
      <a className='text-primary font-bold'>Self-Supervised Learning</a>
        {' '}
        is the foundation for high performing models...
      We are using self-supervised learning in three parts of our application. Help out for free credits to use in your
      video production journey.
    </span>

      {/* Navigation Options */}
      <div className='flex flex-wrap gap-5 justify-center items-center text-white'>

        <a
          href={authState.isAuthenticated ? "/video-matching" : "/authenticate?mode=login"}
          className='bg-white/5 flex flex-col border-primary border  backdrop-blur rounded-xl hover:scale-110 transition-all p-3 justify-center items-center  gap-3 hover:shadow hover:shadow-primary min-w-[150px] max-w-[350px]'>
          <img src={VideoMatching} alt={'landing card image'} className={'mix-blend-darken h-32 w-32 aspect-square'}/>
          <p>Video Matching</p>
          <p>Our machine learning model automatically attempts to encode videos into a vector representation</p>
          <p>However, it's not perfect... </p>
          <a className='text-primary font-bold'>Match Videos</a>
        </a>

        <a
          href={authState.isAuthenticated ? "/segmentation" : "/authenticate?mode=login"}
          className='bg-white/5 flex flex-col border-primary border  backdrop-blur rounded-xl hover:scale-110 transition-all p-3 justify-center items-center  gap-3 hover:shadow hover:shadow-primary min-w-[150px] max-w-[350px]'>
          <img src={VideoMatching} alt={'landing card image'} className={'mix-blend-darken h-32 w-32 aspect-square'}/>
          <p>Segmentation</p>
          <p>Cleaning up our segmentation into more appropriate models, and tracking segments across time.</p>
          <p>This helps our ML model learn how to create nodes in our Deep Graph Learning.</p>
          <a className='text-primary font-bold'>Perform Segmentation</a>
        </a>

        <a
          href={authState.isAuthenticated ? "/404" : "/authenticate?mode=login"}
          className='bg-white/5 flex flex-col border-primary border  backdrop-blur rounded-xl hover:scale-110 transition-all p-3 justify-center items-center  gap-3 hover:shadow hover:shadow-primary min-w-[150px] max-w-[350px]'>
          <img src={VideoMatching} alt={'landing card image'} className={'mix-blend-darken h-32 w-32 aspect-square'}/>
          <p>Video Proposals</p>
          <p>Evaluate the shorts generated by our platform. We're using GPT and chain-of-thought to create these shorts</p>
          <p>Your responses directly feed the model creating better shorts.</p>
          <a className='text-primary font-bold'>Perform Segmentation</a>
        </a>

      </div>

    </div>


  </section>
}